type: files
files:
  - usr: /usr # copy static configurations
              #
              # copies config/files/usr into your image's /usr
              #
              # configuration you wish to end up in /etc/ on the booted system
              # should be added into /usr/etc/ as that is the proper "distro"
              # config directory on ostree. Read more in the files module's README
