type: rpm-ostree
install:
  - bat
  - eza
  - gh
  - htop
  - info
  - neofetch
  - prettyping
  - shellcheck
  - tealdeer
  - telnet
  - zsh

  # @virtualization group
  - virt-install
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - qemu-kvm
  - virt-manager
  - virt-viewer
